//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.26 at 02:52:31 PM IRKT
//


package ru.sibdigital.proccovid.dto.egrul040601;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения об адресе в Российской Федерации в структуре ФИАС, содержащиеся в ЕГРЮЛ
 * 
 * <p>Java class for АдрФИАСЕГРЮЛТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="АдрФИАСЕГРЮЛТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Регион" type="{}CCРФТип"/&gt;
 *         &lt;element name="НаимРегион"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="МуниципРайон" type="{}ВидНаимКодТип" minOccurs="0"/&gt;
 *         &lt;element name="ГородСелПоселен" type="{}ВидНаимКодТип" minOccurs="0"/&gt;
 *         &lt;element name="НаселенПункт" type="{}ВидНаимПТип" minOccurs="0"/&gt;
 *         &lt;element name="ЭлПланСтруктур" type="{}ТипНаимПТип" minOccurs="0"/&gt;
 *         &lt;element name="ЭлУлДорСети" type="{}ТипНаимПТип" minOccurs="0"/&gt;
 *         &lt;element name="Здание" type="{}НомерПТип" maxOccurs="3" minOccurs="0"/&gt;
 *         &lt;element name="ПомещЗдания" type="{}НомерПТип" minOccurs="0"/&gt;
 *         &lt;element name="ПомещКвартиры" type="{}НомерПТип" minOccurs="0"/&gt;
 *         &lt;element name="ГРНДата" type="{}ГРНДатаТип"/&gt;
 *         &lt;element name="ГРНДатаИспр" type="{}ГРНДатаТип" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ИдНом"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="36"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Индекс"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;length value="6"/&gt;
 *             &lt;pattern value="[0-9]{6}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0410\u0434\u0440\u0424\u0418\u0410\u0421\u0415\u0413\u0420\u042e\u041b\u0422\u0438\u043f", propOrder = {
    "\u0440\u0435\u0433\u0438\u043e\u043d",
    "\u043d\u0430\u0438\u043c\u0420\u0435\u0433\u0438\u043e\u043d",
    "\u043c\u0443\u043d\u0438\u0446\u0438\u043f\u0420\u0430\u0439\u043e\u043d",
    "\u0433\u043e\u0440\u043e\u0434\u0421\u0435\u043b\u041f\u043e\u0441\u0435\u043b\u0435\u043d",
    "\u043d\u0430\u0441\u0435\u043b\u0435\u043d\u041f\u0443\u043d\u043a\u0442",
    "\u044d\u043b\u041f\u043b\u0430\u043d\u0421\u0442\u0440\u0443\u043a\u0442\u0443\u0440",
    "\u044d\u043b\u0423\u043b\u0414\u043e\u0440\u0421\u0435\u0442\u0438",
    "\u0437\u0434\u0430\u043d\u0438\u0435",
    "\u043f\u043e\u043c\u0435\u0449\u0417\u0434\u0430\u043d\u0438\u044f",
    "\u043f\u043e\u043c\u0435\u0449\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b",
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430",
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440"
})
public class АдрФИАСЕГРЮЛТип {

    @XmlElement(name = "\u0420\u0435\u0433\u0438\u043e\u043d", required = true)
    protected String регион;
    @XmlElement(name = "\u041d\u0430\u0438\u043c\u0420\u0435\u0433\u0438\u043e\u043d", required = true)
    protected String наимРегион;
    @XmlElement(name = "\u041c\u0443\u043d\u0438\u0446\u0438\u043f\u0420\u0430\u0439\u043e\u043d")
    protected ВидНаимКодТип муниципРайон;
    @XmlElement(name = "\u0413\u043e\u0440\u043e\u0434\u0421\u0435\u043b\u041f\u043e\u0441\u0435\u043b\u0435\u043d")
    protected ВидНаимКодТип городСелПоселен;
    @XmlElement(name = "\u041d\u0430\u0441\u0435\u043b\u0435\u043d\u041f\u0443\u043d\u043a\u0442")
    protected ВидНаимПТип населенПункт;
    @XmlElement(name = "\u042d\u043b\u041f\u043b\u0430\u043d\u0421\u0442\u0440\u0443\u043a\u0442\u0443\u0440")
    protected ТипНаимПТип элПланСтруктур;
    @XmlElement(name = "\u042d\u043b\u0423\u043b\u0414\u043e\u0440\u0421\u0435\u0442\u0438")
    protected ТипНаимПТип элУлДорСети;
    @XmlElement(name = "\u0417\u0434\u0430\u043d\u0438\u0435")
    protected List<НомерПТип> здание;
    @XmlElement(name = "\u041f\u043e\u043c\u0435\u0449\u0417\u0434\u0430\u043d\u0438\u044f")
    protected НомерПТип помещЗдания;
    @XmlElement(name = "\u041f\u043e\u043c\u0435\u0449\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u044b")
    protected НомерПТип помещКвартиры;
    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430", required = true)
    protected ГРНДатаТип грнДата;
    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440")
    protected ГРНДатаТип грнДатаИспр;
    @XmlAttribute(name = "\u0418\u0434\u041d\u043e\u043c")
    protected String идНом;
    @XmlAttribute(name = "\u0418\u043d\u0434\u0435\u043a\u0441")
    protected String индекс;

    /**
     * Gets the value of the регион property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getРегион() {
        return регион;
    }

    /**
     * Sets the value of the регион property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setРегион(String value) {
        this.регион = value;
    }

    /**
     * Gets the value of the наимРегион property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНаимРегион() {
        return наимРегион;
    }

    /**
     * Sets the value of the наимРегион property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНаимРегион(String value) {
        this.наимРегион = value;
    }

    /**
     * Gets the value of the муниципРайон property.
     * 
     * @return
     *     possible object is
     *     {@link ВидНаимКодТип }
     *     
     */
    public ВидНаимКодТип getМуниципРайон() {
        return муниципРайон;
    }

    /**
     * Sets the value of the муниципРайон property.
     * 
     * @param value
     *     allowed object is
     *     {@link ВидНаимКодТип }
     *     
     */
    public void setМуниципРайон(ВидНаимКодТип value) {
        this.муниципРайон = value;
    }

    /**
     * Gets the value of the городСелПоселен property.
     * 
     * @return
     *     possible object is
     *     {@link ВидНаимКодТип }
     *     
     */
    public ВидНаимКодТип getГородСелПоселен() {
        return городСелПоселен;
    }

    /**
     * Sets the value of the городСелПоселен property.
     * 
     * @param value
     *     allowed object is
     *     {@link ВидНаимКодТип }
     *     
     */
    public void setГородСелПоселен(ВидНаимКодТип value) {
        this.городСелПоселен = value;
    }

    /**
     * Gets the value of the населенПункт property.
     * 
     * @return
     *     possible object is
     *     {@link ВидНаимПТип }
     *     
     */
    public ВидНаимПТип getНаселенПункт() {
        return населенПункт;
    }

    /**
     * Sets the value of the населенПункт property.
     * 
     * @param value
     *     allowed object is
     *     {@link ВидНаимПТип }
     *     
     */
    public void setНаселенПункт(ВидНаимПТип value) {
        this.населенПункт = value;
    }

    /**
     * Gets the value of the элПланСтруктур property.
     * 
     * @return
     *     possible object is
     *     {@link ТипНаимПТип }
     *     
     */
    public ТипНаимПТип getЭлПланСтруктур() {
        return элПланСтруктур;
    }

    /**
     * Sets the value of the элПланСтруктур property.
     * 
     * @param value
     *     allowed object is
     *     {@link ТипНаимПТип }
     *     
     */
    public void setЭлПланСтруктур(ТипНаимПТип value) {
        this.элПланСтруктур = value;
    }

    /**
     * Gets the value of the элУлДорСети property.
     * 
     * @return
     *     possible object is
     *     {@link ТипНаимПТип }
     *     
     */
    public ТипНаимПТип getЭлУлДорСети() {
        return элУлДорСети;
    }

    /**
     * Sets the value of the элУлДорСети property.
     * 
     * @param value
     *     allowed object is
     *     {@link ТипНаимПТип }
     *     
     */
    public void setЭлУлДорСети(ТипНаимПТип value) {
        this.элУлДорСети = value;
    }

    /**
     * Gets the value of the здание property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the здание property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getЗдание().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link НомерПТип }
     * 
     * 
     */
    public List<НомерПТип> getЗдание() {
        if (здание == null) {
            здание = new ArrayList<НомерПТип>();
        }
        return this.здание;
    }

    /**
     * Gets the value of the помещЗдания property.
     * 
     * @return
     *     possible object is
     *     {@link НомерПТип }
     *     
     */
    public НомерПТип getПомещЗдания() {
        return помещЗдания;
    }

    /**
     * Sets the value of the помещЗдания property.
     * 
     * @param value
     *     allowed object is
     *     {@link НомерПТип }
     *     
     */
    public void setПомещЗдания(НомерПТип value) {
        this.помещЗдания = value;
    }

    /**
     * Gets the value of the помещКвартиры property.
     * 
     * @return
     *     possible object is
     *     {@link НомерПТип }
     *     
     */
    public НомерПТип getПомещКвартиры() {
        return помещКвартиры;
    }

    /**
     * Sets the value of the помещКвартиры property.
     * 
     * @param value
     *     allowed object is
     *     {@link НомерПТип }
     *     
     */
    public void setПомещКвартиры(НомерПТип value) {
        this.помещКвартиры = value;
    }

    /**
     * Gets the value of the грнДата property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДата() {
        return грнДата;
    }

    /**
     * Sets the value of the грнДата property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДата(ГРНДатаТип value) {
        this.грнДата = value;
    }

    /**
     * Gets the value of the грнДатаИспр property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДатаИспр() {
        return грнДатаИспр;
    }

    /**
     * Sets the value of the грнДатаИспр property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДатаИспр(ГРНДатаТип value) {
        this.грнДатаИспр = value;
    }

    /**
     * Gets the value of the идНом property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдНом() {
        return идНом;
    }

    /**
     * Sets the value of the идНом property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдНом(String value) {
        this.идНом = value;
    }

    /**
     * Gets the value of the индекс property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИндекс() {
        return индекс;
    }

    /**
     * Sets the value of the индекс property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИндекс(String value) {
        this.индекс = value;
    }

}
