//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.26 at 02:52:31 PM IRKT 
//


package ru.sibdigital.proccovid.dto.egrul040601;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения о виде и наименовании адресного элемента
 * 
 * <p>Java class for ВидНаимПТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ВидНаимПТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Вид" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="100"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Наим" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="255"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0412\u0438\u0434\u041d\u0430\u0438\u043c\u041f\u0422\u0438\u043f")
public class ВидНаимПТип {

    @XmlAttribute(name = "\u0412\u0438\u0434", required = true)
    protected String вид;
    @XmlAttribute(name = "\u041d\u0430\u0438\u043c", required = true)
    protected String наим;

    /**
     * Gets the value of the вид property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getВид() {
        return вид;
    }

    /**
     * Sets the value of the вид property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setВид(String value) {
        this.вид = value;
    }

    /**
     * Gets the value of the наим property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНаим() {
        return наим;
    }

    /**
     * Sets the value of the наим property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНаим(String value) {
        this.наим = value;
    }

}
