//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.28 at 09:33:49 AM IRKT 
//


package ru.sibdigital.proccovid.dto.egrul040601;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения о доверительном управляющем - физическом лице
 * 
 * <p>Java class for СвДовУпрФЛТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="СвДовУпрФЛТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ГРНДатаПерв" type="{}ГРНДатаТип" minOccurs="0"/&gt;
 *         &lt;element name="СвФЛ" type="{}СвФЛЕГРЮЛТип"/&gt;
 *         &lt;element name="СвПолФЛ" type="{}СвПолФЛТип" minOccurs="0"/&gt;
 *         &lt;element name="СвРождФЛ" type="{}СвРождЕГРЮЛТип" minOccurs="0"/&gt;
 *         &lt;element name="СвГраждФЛ" type="{}СвГраждТип" minOccurs="0"/&gt;
 *         &lt;element name="УдЛичнФЛ" type="{}УдЛичнЕГРЮЛТип" minOccurs="0"/&gt;
 *         &lt;element name="АдресМЖРФ" type="{}АдрРФЕГРЮЛТип" minOccurs="0"/&gt;
 *         &lt;element name="АдрМЖИн" type="{}АдрИнЕГРЮЛТип" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ОГРНИП" type="{}ОГРНИПТип" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0421\u0432\u0414\u043e\u0432\u0423\u043f\u0440\u0424\u041b\u0422\u0438\u043f", propOrder = {
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430\u041f\u0435\u0440\u0432",
    "\u0441\u0432\u0424\u041b",
    "\u0441\u0432\u041f\u043e\u043b\u0424\u041b",
    "\u0441\u0432\u0420\u043e\u0436\u0434\u0424\u041b",
    "\u0441\u0432\u0413\u0440\u0430\u0436\u0434\u0424\u041b",
    "\u0443\u0434\u041b\u0438\u0447\u043d\u0424\u041b",
    "\u0430\u0434\u0440\u0435\u0441\u041c\u0416\u0420\u0424",
    "\u0430\u0434\u0440\u041c\u0416\u0418\u043d"
})
public class СвДовУпрФЛТип {

    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430\u041f\u0435\u0440\u0432")
    protected ГРНДатаТип грнДатаПерв;
    @XmlElement(name = "\u0421\u0432\u0424\u041b", required = true)
    protected СвФЛЕГРЮЛТип свФЛ;
    @XmlElement(name = "\u0421\u0432\u041f\u043e\u043b\u0424\u041b")
    protected СвПолФЛТип свПолФЛ;
    @XmlElement(name = "\u0421\u0432\u0420\u043e\u0436\u0434\u0424\u041b")
    protected СвРождЕГРЮЛТип свРождФЛ;
    @XmlElement(name = "\u0421\u0432\u0413\u0440\u0430\u0436\u0434\u0424\u041b")
    protected СвГраждТип свГраждФЛ;
    @XmlElement(name = "\u0423\u0434\u041b\u0438\u0447\u043d\u0424\u041b")
    protected УдЛичнЕГРЮЛТип удЛичнФЛ;
    @XmlElement(name = "\u0410\u0434\u0440\u0435\u0441\u041c\u0416\u0420\u0424")
    protected АдрРФЕГРЮЛТип адресМЖРФ;
    @XmlElement(name = "\u0410\u0434\u0440\u041c\u0416\u0418\u043d")
    protected АдрИнЕГРЮЛТип адрМЖИн;
    @XmlAttribute(name = "\u041e\u0413\u0420\u041d\u0418\u041f")
    protected String огрнип;

    /**
     * Gets the value of the грнДатаПерв property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДатаПерв() {
        return грнДатаПерв;
    }

    /**
     * Sets the value of the грнДатаПерв property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДатаПерв(ГРНДатаТип value) {
        this.грнДатаПерв = value;
    }

    /**
     * Gets the value of the свФЛ property.
     * 
     * @return
     *     possible object is
     *     {@link СвФЛЕГРЮЛТип }
     *     
     */
    public СвФЛЕГРЮЛТип getСвФЛ() {
        return свФЛ;
    }

    /**
     * Sets the value of the свФЛ property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвФЛЕГРЮЛТип }
     *     
     */
    public void setСвФЛ(СвФЛЕГРЮЛТип value) {
        this.свФЛ = value;
    }

    /**
     * Gets the value of the свПолФЛ property.
     * 
     * @return
     *     possible object is
     *     {@link СвПолФЛТип }
     *     
     */
    public СвПолФЛТип getСвПолФЛ() {
        return свПолФЛ;
    }

    /**
     * Sets the value of the свПолФЛ property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвПолФЛТип }
     *     
     */
    public void setСвПолФЛ(СвПолФЛТип value) {
        this.свПолФЛ = value;
    }

    /**
     * Gets the value of the свРождФЛ property.
     * 
     * @return
     *     possible object is
     *     {@link СвРождЕГРЮЛТип }
     *     
     */
    public СвРождЕГРЮЛТип getСвРождФЛ() {
        return свРождФЛ;
    }

    /**
     * Sets the value of the свРождФЛ property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвРождЕГРЮЛТип }
     *     
     */
    public void setСвРождФЛ(СвРождЕГРЮЛТип value) {
        this.свРождФЛ = value;
    }

    /**
     * Gets the value of the свГраждФЛ property.
     * 
     * @return
     *     possible object is
     *     {@link СвГраждТип }
     *     
     */
    public СвГраждТип getСвГраждФЛ() {
        return свГраждФЛ;
    }

    /**
     * Sets the value of the свГраждФЛ property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвГраждТип }
     *     
     */
    public void setСвГраждФЛ(СвГраждТип value) {
        this.свГраждФЛ = value;
    }

    /**
     * Gets the value of the удЛичнФЛ property.
     * 
     * @return
     *     possible object is
     *     {@link УдЛичнЕГРЮЛТип }
     *     
     */
    public УдЛичнЕГРЮЛТип getУдЛичнФЛ() {
        return удЛичнФЛ;
    }

    /**
     * Sets the value of the удЛичнФЛ property.
     * 
     * @param value
     *     allowed object is
     *     {@link УдЛичнЕГРЮЛТип }
     *     
     */
    public void setУдЛичнФЛ(УдЛичнЕГРЮЛТип value) {
        this.удЛичнФЛ = value;
    }

    /**
     * Gets the value of the адресМЖРФ property.
     * 
     * @return
     *     possible object is
     *     {@link АдрРФЕГРЮЛТип }
     *     
     */
    public АдрРФЕГРЮЛТип getАдресМЖРФ() {
        return адресМЖРФ;
    }

    /**
     * Sets the value of the адресМЖРФ property.
     * 
     * @param value
     *     allowed object is
     *     {@link АдрРФЕГРЮЛТип }
     *     
     */
    public void setАдресМЖРФ(АдрРФЕГРЮЛТип value) {
        this.адресМЖРФ = value;
    }

    /**
     * Gets the value of the адрМЖИн property.
     * 
     * @return
     *     possible object is
     *     {@link АдрИнЕГРЮЛТип }
     *     
     */
    public АдрИнЕГРЮЛТип getАдрМЖИн() {
        return адрМЖИн;
    }

    /**
     * Sets the value of the адрМЖИн property.
     * 
     * @param value
     *     allowed object is
     *     {@link АдрИнЕГРЮЛТип }
     *     
     */
    public void setАдрМЖИн(АдрИнЕГРЮЛТип value) {
        this.адрМЖИн = value;
    }

    /**
     * Gets the value of the огрнип property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОГРНИП() {
        return огрнип;
    }

    /**
     * Sets the value of the огрнип property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОГРНИП(String value) {
        this.огрнип = value;
    }

}
