//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.28 at 09:33:49 AM IRKT 
//


package ru.sibdigital.proccovid.dto.egrul040601;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Сведения о доверительном управляющем - российском или иностранном юридическом лице
 * 
 * <p>Java class for СвДовУпрЮЛТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="СвДовУпрЮЛТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ГРНДатаПерв" type="{}ГРНДатаТип" minOccurs="0"/&gt;
 *         &lt;element name="НаимИННДовУпр" type="{}СвЮЛЕГРЮЛТип"/&gt;
 *         &lt;element name="СвНаимЮЛПолнИн" type="{}СвНаимПолнТип" minOccurs="0"/&gt;
 *         &lt;element name="СвРегИн" type="{}СвРегИнЮЛЕГРЮЛТип" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ДатаОткрНасл" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0421\u0432\u0414\u043e\u0432\u0423\u043f\u0440\u042e\u041b\u0422\u0438\u043f", propOrder = {
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430\u041f\u0435\u0440\u0432",
    "\u043d\u0430\u0438\u043c\u0418\u041d\u041d\u0414\u043e\u0432\u0423\u043f\u0440",
    "\u0441\u0432\u041d\u0430\u0438\u043c\u042e\u041b\u041f\u043e\u043b\u043d\u0418\u043d",
    "\u0441\u0432\u0420\u0435\u0433\u0418\u043d"
})
public class СвДовУпрЮЛТип {

    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430\u041f\u0435\u0440\u0432")
    protected ГРНДатаТип грнДатаПерв;
    @XmlElement(name = "\u041d\u0430\u0438\u043c\u0418\u041d\u041d\u0414\u043e\u0432\u0423\u043f\u0440", required = true)
    protected СвЮЛЕГРЮЛТип наимИННДовУпр;
    @XmlElement(name = "\u0421\u0432\u041d\u0430\u0438\u043c\u042e\u041b\u041f\u043e\u043b\u043d\u0418\u043d")
    protected СвНаимПолнТип свНаимЮЛПолнИн;
    @XmlElement(name = "\u0421\u0432\u0420\u0435\u0433\u0418\u043d")
    protected СвРегИнЮЛЕГРЮЛТип свРегИн;
    @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u041e\u0442\u043a\u0440\u041d\u0430\u0441\u043b")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar датаОткрНасл;

    /**
     * Gets the value of the грнДатаПерв property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДатаПерв() {
        return грнДатаПерв;
    }

    /**
     * Sets the value of the грнДатаПерв property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДатаПерв(ГРНДатаТип value) {
        this.грнДатаПерв = value;
    }

    /**
     * Gets the value of the наимИННДовУпр property.
     * 
     * @return
     *     possible object is
     *     {@link СвЮЛЕГРЮЛТип }
     *     
     */
    public СвЮЛЕГРЮЛТип getНаимИННДовУпр() {
        return наимИННДовУпр;
    }

    /**
     * Sets the value of the наимИННДовУпр property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвЮЛЕГРЮЛТип }
     *     
     */
    public void setНаимИННДовУпр(СвЮЛЕГРЮЛТип value) {
        this.наимИННДовУпр = value;
    }

    /**
     * Gets the value of the свНаимЮЛПолнИн property.
     * 
     * @return
     *     possible object is
     *     {@link СвНаимПолнТип }
     *     
     */
    public СвНаимПолнТип getСвНаимЮЛПолнИн() {
        return свНаимЮЛПолнИн;
    }

    /**
     * Sets the value of the свНаимЮЛПолнИн property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвНаимПолнТип }
     *     
     */
    public void setСвНаимЮЛПолнИн(СвНаимПолнТип value) {
        this.свНаимЮЛПолнИн = value;
    }

    /**
     * Gets the value of the свРегИн property.
     * 
     * @return
     *     possible object is
     *     {@link СвРегИнЮЛЕГРЮЛТип }
     *     
     */
    public СвРегИнЮЛЕГРЮЛТип getСвРегИн() {
        return свРегИн;
    }

    /**
     * Sets the value of the свРегИн property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвРегИнЮЛЕГРЮЛТип }
     *     
     */
    public void setСвРегИн(СвРегИнЮЛЕГРЮЛТип value) {
        this.свРегИн = value;
    }

    /**
     * Gets the value of the датаОткрНасл property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getДатаОткрНасл() {
        return датаОткрНасл;
    }

    /**
     * Sets the value of the датаОткрНасл property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setДатаОткрНасл(XMLGregorianCalendar value) {
        this.датаОткрНасл = value;
    }

}
