//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.26 at 02:52:31 PM IRKT 
//


package ru.sibdigital.proccovid.dto.egrul040601;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Сведения о регистрации иностранного юридического лица в стране происхождения, содержащиеся в ЕГРЮЛ
 * 
 * <p>Java class for СвРегИнЮЛЕГРЮЛТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="СвРегИнЮЛЕГРЮЛТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ГРНДата" type="{}ГРНДатаТип"/&gt;
 *         &lt;element name="ГРНДатаИспр" type="{}ГРНДатаТип" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ОКСМ" use="required" type="{}ОКСМТип" /&gt;
 *       &lt;attribute name="НаимСтран" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="250"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ДатаРег" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="РегНомер"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="255"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="НаимРегОрг"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="1000"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="КодНПСтрРег"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="50"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="АдрСтр"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="510"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0421\u0432\u0420\u0435\u0433\u0418\u043d\u042e\u041b\u0415\u0413\u0420\u042e\u041b\u0422\u0438\u043f", propOrder = {
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430",
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440"
})
public class СвРегИнЮЛЕГРЮЛТип {

    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430", required = true)
    protected ГРНДатаТип грнДата;
    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440")
    protected ГРНДатаТип грнДатаИспр;
    @XmlAttribute(name = "\u041e\u041a\u0421\u041c", required = true)
    protected String оксм;
    @XmlAttribute(name = "\u041d\u0430\u0438\u043c\u0421\u0442\u0440\u0430\u043d", required = true)
    protected String наимСтран;
    @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u0420\u0435\u0433")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar датаРег;
    @XmlAttribute(name = "\u0420\u0435\u0433\u041d\u043e\u043c\u0435\u0440")
    protected String регНомер;
    @XmlAttribute(name = "\u041d\u0430\u0438\u043c\u0420\u0435\u0433\u041e\u0440\u0433")
    protected String наимРегОрг;
    @XmlAttribute(name = "\u041a\u043e\u0434\u041d\u041f\u0421\u0442\u0440\u0420\u0435\u0433")
    protected String кодНПСтрРег;
    @XmlAttribute(name = "\u0410\u0434\u0440\u0421\u0442\u0440")
    protected String адрСтр;

    /**
     * Gets the value of the грнДата property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДата() {
        return грнДата;
    }

    /**
     * Sets the value of the грнДата property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДата(ГРНДатаТип value) {
        this.грнДата = value;
    }

    /**
     * Gets the value of the грнДатаИспр property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДатаИспр() {
        return грнДатаИспр;
    }

    /**
     * Sets the value of the грнДатаИспр property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДатаИспр(ГРНДатаТип value) {
        this.грнДатаИспр = value;
    }

    /**
     * Gets the value of the оксм property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОКСМ() {
        return оксм;
    }

    /**
     * Sets the value of the оксм property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОКСМ(String value) {
        this.оксм = value;
    }

    /**
     * Gets the value of the наимСтран property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНаимСтран() {
        return наимСтран;
    }

    /**
     * Sets the value of the наимСтран property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНаимСтран(String value) {
        this.наимСтран = value;
    }

    /**
     * Gets the value of the датаРег property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getДатаРег() {
        return датаРег;
    }

    /**
     * Sets the value of the датаРег property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setДатаРег(XMLGregorianCalendar value) {
        this.датаРег = value;
    }

    /**
     * Gets the value of the регНомер property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getРегНомер() {
        return регНомер;
    }

    /**
     * Sets the value of the регНомер property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setРегНомер(String value) {
        this.регНомер = value;
    }

    /**
     * Gets the value of the наимРегОрг property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНаимРегОрг() {
        return наимРегОрг;
    }

    /**
     * Sets the value of the наимРегОрг property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНаимРегОрг(String value) {
        this.наимРегОрг = value;
    }

    /**
     * Gets the value of the кодНПСтрРег property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКодНПСтрРег() {
        return кодНПСтрРег;
    }

    /**
     * Sets the value of the кодНПСтрРег property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКодНПСтрРег(String value) {
        this.кодНПСтрРег = value;
    }

    /**
     * Gets the value of the адрСтр property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getАдрСтр() {
        return адрСтр;
    }

    /**
     * Sets the value of the адрСтр property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setАдрСтр(String value) {
        this.адрСтр = value;
    }

}
