//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.26 at 02:52:31 PM IRKT 
//


package ru.sibdigital.proccovid.dto.egrul040601;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения об управляющих залогом доли участника
 * 
 * <p>Java class for СвУправЗалТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="СвУправЗалТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ГРНДатаПерв" type="{}ГРНДатаТип" minOccurs="0"/&gt;
 *         &lt;element name="СвНотУдДогЗал" type="{}СвНотУдДогЗалТип"/&gt;
 *         &lt;element name="СвДогУправЗал" type="{}СвНотУдДогЗалТип"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="СвУпрЗалФЛ"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="СвФЛ" type="{}СвФЛЕГРЮЛТип"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;attribute name="ОГРНИП" use="required" type="{}ОГРНИПТип" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="СвУпрЗалЮЛ"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="НаимИННЮЛ" type="{}СвЮЛЕГРЮЛТип"/&gt;
 *                     &lt;element name="СвНаимЮЛПолнИн" type="{}СвНаимПолнТип" minOccurs="0"/&gt;
 *                     &lt;element name="СвРегИн" type="{}СвРегИнЮЛЕГРЮЛТип" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0421\u0432\u0423\u043f\u0440\u0430\u0432\u0417\u0430\u043b\u0422\u0438\u043f", propOrder = {
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430\u041f\u0435\u0440\u0432",
    "\u0441\u0432\u041d\u043e\u0442\u0423\u0434\u0414\u043e\u0433\u0417\u0430\u043b",
    "\u0441\u0432\u0414\u043e\u0433\u0423\u043f\u0440\u0430\u0432\u0417\u0430\u043b",
    "\u0441\u0432\u0423\u043f\u0440\u0417\u0430\u043b\u0424\u041b",
    "\u0441\u0432\u0423\u043f\u0440\u0417\u0430\u043b\u042e\u041b"
})
public class СвУправЗалТип {

    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430\u041f\u0435\u0440\u0432")
    protected ГРНДатаТип грнДатаПерв;
    @XmlElement(name = "\u0421\u0432\u041d\u043e\u0442\u0423\u0434\u0414\u043e\u0433\u0417\u0430\u043b", required = true)
    protected СвНотУдДогЗалТип свНотУдДогЗал;
    @XmlElement(name = "\u0421\u0432\u0414\u043e\u0433\u0423\u043f\u0440\u0430\u0432\u0417\u0430\u043b", required = true)
    protected СвНотУдДогЗалТип свДогУправЗал;
    @XmlElement(name = "\u0421\u0432\u0423\u043f\u0440\u0417\u0430\u043b\u0424\u041b")
    protected СвУправЗалТип.СвУпрЗалФЛ свУпрЗалФЛ;
    @XmlElement(name = "\u0421\u0432\u0423\u043f\u0440\u0417\u0430\u043b\u042e\u041b")
    protected СвУправЗалТип.СвУпрЗалЮЛ свУпрЗалЮЛ;

    /**
     * Gets the value of the грнДатаПерв property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДатаПерв() {
        return грнДатаПерв;
    }

    /**
     * Sets the value of the грнДатаПерв property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДатаПерв(ГРНДатаТип value) {
        this.грнДатаПерв = value;
    }

    /**
     * Gets the value of the свНотУдДогЗал property.
     * 
     * @return
     *     possible object is
     *     {@link СвНотУдДогЗалТип }
     *     
     */
    public СвНотУдДогЗалТип getСвНотУдДогЗал() {
        return свНотУдДогЗал;
    }

    /**
     * Sets the value of the свНотУдДогЗал property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвНотУдДогЗалТип }
     *     
     */
    public void setСвНотУдДогЗал(СвНотУдДогЗалТип value) {
        this.свНотУдДогЗал = value;
    }

    /**
     * Gets the value of the свДогУправЗал property.
     * 
     * @return
     *     possible object is
     *     {@link СвНотУдДогЗалТип }
     *     
     */
    public СвНотУдДогЗалТип getСвДогУправЗал() {
        return свДогУправЗал;
    }

    /**
     * Sets the value of the свДогУправЗал property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвНотУдДогЗалТип }
     *     
     */
    public void setСвДогУправЗал(СвНотУдДогЗалТип value) {
        this.свДогУправЗал = value;
    }

    /**
     * Gets the value of the свУпрЗалФЛ property.
     * 
     * @return
     *     possible object is
     *     {@link СвУправЗалТип.СвУпрЗалФЛ }
     *     
     */
    public СвУправЗалТип.СвУпрЗалФЛ getСвУпрЗалФЛ() {
        return свУпрЗалФЛ;
    }

    /**
     * Sets the value of the свУпрЗалФЛ property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвУправЗалТип.СвУпрЗалФЛ }
     *     
     */
    public void setСвУпрЗалФЛ(СвУправЗалТип.СвУпрЗалФЛ value) {
        this.свУпрЗалФЛ = value;
    }

    /**
     * Gets the value of the свУпрЗалЮЛ property.
     * 
     * @return
     *     possible object is
     *     {@link СвУправЗалТип.СвУпрЗалЮЛ }
     *     
     */
    public СвУправЗалТип.СвУпрЗалЮЛ getСвУпрЗалЮЛ() {
        return свУпрЗалЮЛ;
    }

    /**
     * Sets the value of the свУпрЗалЮЛ property.
     * 
     * @param value
     *     allowed object is
     *     {@link СвУправЗалТип.СвУпрЗалЮЛ }
     *     
     */
    public void setСвУпрЗалЮЛ(СвУправЗалТип.СвУпрЗалЮЛ value) {
        this.свУпрЗалЮЛ = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="СвФЛ" type="{}СвФЛЕГРЮЛТип"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="ОГРНИП" use="required" type="{}ОГРНИПТип" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0441\u0432\u0424\u041b"
    })
    public static class СвУпрЗалФЛ {

        @XmlElement(name = "\u0421\u0432\u0424\u041b", required = true)
        protected СвФЛЕГРЮЛТип свФЛ;
        @XmlAttribute(name = "\u041e\u0413\u0420\u041d\u0418\u041f", required = true)
        protected String огрнип;

        /**
         * Gets the value of the свФЛ property.
         * 
         * @return
         *     possible object is
         *     {@link СвФЛЕГРЮЛТип }
         *     
         */
        public СвФЛЕГРЮЛТип getСвФЛ() {
            return свФЛ;
        }

        /**
         * Sets the value of the свФЛ property.
         * 
         * @param value
         *     allowed object is
         *     {@link СвФЛЕГРЮЛТип }
         *     
         */
        public void setСвФЛ(СвФЛЕГРЮЛТип value) {
            this.свФЛ = value;
        }

        /**
         * Gets the value of the огрнип property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getОГРНИП() {
            return огрнип;
        }

        /**
         * Sets the value of the огрнип property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setОГРНИП(String value) {
            this.огрнип = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="НаимИННЮЛ" type="{}СвЮЛЕГРЮЛТип"/&gt;
     *         &lt;element name="СвНаимЮЛПолнИн" type="{}СвНаимПолнТип" minOccurs="0"/&gt;
     *         &lt;element name="СвРегИн" type="{}СвРегИнЮЛЕГРЮЛТип" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043d\u0430\u0438\u043c\u0418\u041d\u041d\u042e\u041b",
        "\u0441\u0432\u041d\u0430\u0438\u043c\u042e\u041b\u041f\u043e\u043b\u043d\u0418\u043d",
        "\u0441\u0432\u0420\u0435\u0433\u0418\u043d"
    })
    public static class СвУпрЗалЮЛ {

        @XmlElement(name = "\u041d\u0430\u0438\u043c\u0418\u041d\u041d\u042e\u041b", required = true)
        protected СвЮЛЕГРЮЛТип наимИННЮЛ;
        @XmlElement(name = "\u0421\u0432\u041d\u0430\u0438\u043c\u042e\u041b\u041f\u043e\u043b\u043d\u0418\u043d")
        protected СвНаимПолнТип свНаимЮЛПолнИн;
        @XmlElement(name = "\u0421\u0432\u0420\u0435\u0433\u0418\u043d")
        protected СвРегИнЮЛЕГРЮЛТип свРегИн;

        /**
         * Gets the value of the наимИННЮЛ property.
         * 
         * @return
         *     possible object is
         *     {@link СвЮЛЕГРЮЛТип }
         *     
         */
        public СвЮЛЕГРЮЛТип getНаимИННЮЛ() {
            return наимИННЮЛ;
        }

        /**
         * Sets the value of the наимИННЮЛ property.
         * 
         * @param value
         *     allowed object is
         *     {@link СвЮЛЕГРЮЛТип }
         *     
         */
        public void setНаимИННЮЛ(СвЮЛЕГРЮЛТип value) {
            this.наимИННЮЛ = value;
        }

        /**
         * Gets the value of the свНаимЮЛПолнИн property.
         * 
         * @return
         *     possible object is
         *     {@link СвНаимПолнТип }
         *     
         */
        public СвНаимПолнТип getСвНаимЮЛПолнИн() {
            return свНаимЮЛПолнИн;
        }

        /**
         * Sets the value of the свНаимЮЛПолнИн property.
         * 
         * @param value
         *     allowed object is
         *     {@link СвНаимПолнТип }
         *     
         */
        public void setСвНаимЮЛПолнИн(СвНаимПолнТип value) {
            this.свНаимЮЛПолнИн = value;
        }

        /**
         * Gets the value of the свРегИн property.
         * 
         * @return
         *     possible object is
         *     {@link СвРегИнЮЛЕГРЮЛТип }
         *     
         */
        public СвРегИнЮЛЕГРЮЛТип getСвРегИн() {
            return свРегИн;
        }

        /**
         * Sets the value of the свРегИн property.
         * 
         * @param value
         *     allowed object is
         *     {@link СвРегИнЮЛЕГРЮЛТип }
         *     
         */
        public void setСвРегИн(СвРегИнЮЛЕГРЮЛТип value) {
            this.свРегИн = value;
        }

    }

}
