//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.26 at 02:54:32 PM IRKT 
//


package ru.sibdigital.proccovid.dto.egrip040501;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.sibdigital.proccovid.dto.egrip040501 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.sibdigital.proccovid.dto.egrip040501
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Файл }
     * 
     */
    public Файл createФайл() {
        return new Файл();
    }

    /**
     * Create an instance of {@link Файл.Документ }
     * 
     */
    public Файл.Документ createФайлДокумент() {
        return new Файл.Документ();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП }
     * 
     */
    public Файл.Документ.СвИП createФайлДокументСвИП() {
        return new Файл.Документ.СвИП();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвЗапЕГРИП }
     * 
     */
    public Файл.Документ.СвИП.СвЗапЕГРИП createФайлДокументСвИПСвЗапЕГРИП() {
        return new Файл.Документ.СвИП.СвЗапЕГРИП();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвЛицензия }
     * 
     */
    public Файл.Документ.СвИП.СвЛицензия createФайлДокументСвИПСвЛицензия() {
        return new Файл.Документ.СвИП.СвЛицензия();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвРегФСС }
     * 
     */
    public Файл.Документ.СвИП.СвРегФСС createФайлДокументСвИПСвРегФСС() {
        return new Файл.Документ.СвИП.СвРегФСС();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвРегПФ }
     * 
     */
    public Файл.Документ.СвИП.СвРегПФ createФайлДокументСвИПСвРегПФ() {
        return new Файл.Документ.СвИП.СвРегПФ();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвУчетНО }
     * 
     */
    public Файл.Документ.СвИП.СвУчетНО createФайлДокументСвИПСвУчетНО() {
        return new Файл.Документ.СвИП.СвУчетНО();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвПрекращ }
     * 
     */
    public Файл.Документ.СвИП.СвПрекращ createФайлДокументСвИПСвПрекращ() {
        return new Файл.Документ.СвИП.СвПрекращ();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвСтатус }
     * 
     */
    public Файл.Документ.СвИП.СвСтатус createФайлДокументСвИПСвСтатус() {
        return new Файл.Документ.СвИП.СвСтатус();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвРегИП }
     * 
     */
    public Файл.Документ.СвИП.СвРегИП createФайлДокументСвИПСвРегИП() {
        return new Файл.Документ.СвИП.СвРегИП();
    }

    /**
     * Create an instance of {@link Файл.ИдОтпр }
     * 
     */
    public Файл.ИдОтпр createФайлИдОтпр() {
        return new Файл.ИдОтпр();
    }

    /**
     * Create an instance of {@link АдрРФТипВып }
     * 
     */
    public АдрРФТипВып createАдрРФТипВып() {
        return new АдрРФТипВып();
    }

    /**
     * Create an instance of {@link АдрФИАСЕГРИПТип }
     * 
     */
    public АдрФИАСЕГРИПТип createАдрФИАСЕГРИПТип() {
        return new АдрФИАСЕГРИПТип();
    }

    /**
     * Create an instance of {@link ВидЗапТип }
     * 
     */
    public ВидЗапТип createВидЗапТип() {
        return new ВидЗапТип();
    }

    /**
     * Create an instance of {@link ВидНаимКодТип }
     * 
     */
    public ВидНаимКодТип createВидНаимКодТип() {
        return new ВидНаимКодТип();
    }

    /**
     * Create an instance of {@link ВидНаимПТип }
     * 
     */
    public ВидНаимПТип createВидНаимПТип() {
        return new ВидНаимПТип();
    }

    /**
     * Create an instance of {@link ТипНаимПТип }
     * 
     */
    public ТипНаимПТип createТипНаимПТип() {
        return new ТипНаимПТип();
    }

    /**
     * Create an instance of {@link НомерПТип }
     * 
     */
    public НомерПТип createНомерПТип() {
        return new НомерПТип();
    }

    /**
     * Create an instance of {@link ГородТип }
     * 
     */
    public ГородТип createГородТип() {
        return new ГородТип();
    }

    /**
     * Create an instance of {@link ГРНИПДатаТип }
     * 
     */
    public ГРНИПДатаТип createГРНИПДатаТип() {
        return new ГРНИПДатаТип();
    }

    /**
     * Create an instance of {@link ИдГРНИПДатаТип }
     * 
     */
    public ИдГРНИПДатаТип createИдГРНИПДатаТип() {
        return new ИдГРНИПДатаТип();
    }

    /**
     * Create an instance of {@link НаселПунктТип }
     * 
     */
    public НаселПунктТип createНаселПунктТип() {
        return new НаселПунктТип();
    }

    /**
     * Create an instance of {@link РайонТип }
     * 
     */
    public РайонТип createРайонТип() {
        return new РайонТип();
    }

    /**
     * Create an instance of {@link РегионТип }
     * 
     */
    public РегионТип createРегионТип() {
        return new РегионТип();
    }

    /**
     * Create an instance of {@link СвОКВЭДТип }
     * 
     */
    public СвОКВЭДТип createСвОКВЭДТип() {
        return new СвОКВЭДТип();
    }

    /**
     * Create an instance of {@link СвРегОргТип }
     * 
     */
    public СвРегОргТип createСвРегОргТип() {
        return new СвРегОргТип();
    }

    /**
     * Create an instance of {@link УдЛичнТипР }
     * 
     */
    public УдЛичнТипР createУдЛичнТипР() {
        return new УдЛичнТипР();
    }

    /**
     * Create an instance of {@link СвФИОЗАГСТип }
     * 
     */
    public СвФИОЗАГСТип createСвФИОЗАГСТип() {
        return new СвФИОЗАГСТип();
    }

    /**
     * Create an instance of {@link УлицаТип }
     * 
     */
    public УлицаТип createУлицаТип() {
        return new УлицаТип();
    }

    /**
     * Create an instance of {@link ФИО1Тип }
     * 
     */
    public ФИО1Тип createФИО1Тип() {
        return new ФИО1Тип();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвФЛ }
     * 
     */
    public Файл.Документ.СвИП.СвФЛ createФайлДокументСвИПСвФЛ() {
        return new Файл.Документ.СвИП.СвФЛ();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвРожд }
     * 
     */
    public Файл.Документ.СвИП.СвРожд createФайлДокументСвИПСвРожд() {
        return new Файл.Документ.СвИП.СвРожд();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвГражд }
     * 
     */
    public Файл.Документ.СвИП.СвГражд createФайлДокументСвИПСвГражд() {
        return new Файл.Документ.СвИП.СвГражд();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвУдЛичнФЛ }
     * 
     */
    public Файл.Документ.СвИП.СвУдЛичнФЛ createФайлДокументСвИПСвУдЛичнФЛ() {
        return new Файл.Документ.СвИП.СвУдЛичнФЛ();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвПравЖитРФ }
     * 
     */
    public Файл.Документ.СвИП.СвПравЖитРФ createФайлДокументСвИПСвПравЖитРФ() {
        return new Файл.Документ.СвИП.СвПравЖитРФ();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвАдрМЖ }
     * 
     */
    public Файл.Документ.СвИП.СвАдрМЖ createФайлДокументСвИПСвАдрМЖ() {
        return new Файл.Документ.СвИП.СвАдрМЖ();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвАдрЭлПочты }
     * 
     */
    public Файл.Документ.СвИП.СвАдрЭлПочты createФайлДокументСвИПСвАдрЭлПочты() {
        return new Файл.Документ.СвИП.СвАдрЭлПочты();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвРегОрг }
     * 
     */
    public Файл.Документ.СвИП.СвРегОрг createФайлДокументСвИПСвРегОрг() {
        return new Файл.Документ.СвИП.СвРегОрг();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвОКВЭД }
     * 
     */
    public Файл.Документ.СвИП.СвОКВЭД createФайлДокументСвИПСвОКВЭД() {
        return new Файл.Документ.СвИП.СвОКВЭД();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвЗапЕГРИП.СведПредДок }
     * 
     */
    public Файл.Документ.СвИП.СвЗапЕГРИП.СведПредДок createФайлДокументСвИПСвЗапЕГРИПСведПредДок() {
        return new Файл.Документ.СвИП.СвЗапЕГРИП.СведПредДок();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвЗапЕГРИП.СвСвид }
     * 
     */
    public Файл.Документ.СвИП.СвЗапЕГРИП.СвСвид createФайлДокументСвИПСвЗапЕГРИПСвСвид() {
        return new Файл.Документ.СвИП.СвЗапЕГРИП.СвСвид();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвЗапЕГРИП.СвСтатусЗап }
     * 
     */
    public Файл.Документ.СвИП.СвЗапЕГРИП.СвСтатусЗап createФайлДокументСвИПСвЗапЕГРИПСвСтатусЗап() {
        return new Файл.Документ.СвИП.СвЗапЕГРИП.СвСтатусЗап();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвЛицензия.СвПриостЛиц }
     * 
     */
    public Файл.Документ.СвИП.СвЛицензия.СвПриостЛиц createФайлДокументСвИПСвЛицензияСвПриостЛиц() {
        return new Файл.Документ.СвИП.СвЛицензия.СвПриостЛиц();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвРегФСС.СвОргФСС }
     * 
     */
    public Файл.Документ.СвИП.СвРегФСС.СвОргФСС createФайлДокументСвИПСвРегФСССвОргФСС() {
        return new Файл.Документ.СвИП.СвРегФСС.СвОргФСС();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвРегПФ.СвОргПФ }
     * 
     */
    public Файл.Документ.СвИП.СвРегПФ.СвОргПФ createФайлДокументСвИПСвРегПФСвОргПФ() {
        return new Файл.Документ.СвИП.СвРегПФ.СвОргПФ();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвУчетНО.СвНО }
     * 
     */
    public Файл.Документ.СвИП.СвУчетНО.СвНО createФайлДокументСвИПСвУчетНОСвНО() {
        return new Файл.Документ.СвИП.СвУчетНО.СвНО();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвПрекращ.СвСтатус }
     * 
     */
    public Файл.Документ.СвИП.СвПрекращ.СвСтатус createФайлДокументСвИПСвПрекращСвСтатус() {
        return new Файл.Документ.СвИП.СвПрекращ.СвСтатус();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвПрекращ.СвНовЮЛ }
     * 
     */
    public Файл.Документ.СвИП.СвПрекращ.СвНовЮЛ createФайлДокументСвИПСвПрекращСвНовЮЛ() {
        return new Файл.Документ.СвИП.СвПрекращ.СвНовЮЛ();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвСтатус.СвСтатус1 }
     * 
     */
    public Файл.Документ.СвИП.СвСтатус.СвСтатус1 createФайлДокументСвИПСвСтатусСвСтатус() {
        return new Файл.Документ.СвИП.СвСтатус.СвСтатус1();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвСтатус.СвРешИсклИП }
     * 
     */
    public Файл.Документ.СвИП.СвСтатус.СвРешИсклИП createФайлДокументСвИПСвСтатусСвРешИсклИП() {
        return new Файл.Документ.СвИП.СвСтатус.СвРешИсклИП();
    }

    /**
     * Create an instance of {@link Файл.Документ.СвИП.СвРегИП.СвКФХ }
     * 
     */
    public Файл.Документ.СвИП.СвРегИП.СвКФХ createФайлДокументСвИПСвРегИПСвКФХ() {
        return new Файл.Документ.СвИП.СвРегИП.СвКФХ();
    }

}
