//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.26 at 02:54:32 PM IRKT 
//


package ru.sibdigital.proccovid.dto.egrip040501;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения о фамилии, имени, отчестве физического лица по данным ЗАГС
 * 
 * <p>Java class for СвФИОЗАГСТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="СвФИОЗАГСТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ГРНИПДата" type="{}ГРНИПДатаТип"/&gt;
 *         &lt;element name="ГРНИПДатаИспр" type="{}ГРНИПДатаТип" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Фамилия"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="60"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Имя"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="60"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Отчество"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="60"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0421\u0432\u0424\u0418\u041e\u0417\u0410\u0413\u0421\u0422\u0438\u043f", propOrder = {
    "\u0433\u0440\u043d\u0438\u043f\u0414\u0430\u0442\u0430",
    "\u0433\u0440\u043d\u0438\u043f\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440"
})
public class СвФИОЗАГСТип {

    @XmlElement(name = "\u0413\u0420\u041d\u0418\u041f\u0414\u0430\u0442\u0430", required = true)
    protected ГРНИПДатаТип грнипДата;
    @XmlElement(name = "\u0413\u0420\u041d\u0418\u041f\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440")
    protected ГРНИПДатаТип грнипДатаИспр;
    @XmlAttribute(name = "\u0424\u0430\u043c\u0438\u043b\u0438\u044f")
    protected String фамилия;
    @XmlAttribute(name = "\u0418\u043c\u044f")
    protected String имя;
    @XmlAttribute(name = "\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e")
    protected String отчество;

    /**
     * Gets the value of the грнипДата property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНИПДатаТип }
     *     
     */
    public ГРНИПДатаТип getГРНИПДата() {
        return грнипДата;
    }

    /**
     * Sets the value of the грнипДата property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНИПДатаТип }
     *     
     */
    public void setГРНИПДата(ГРНИПДатаТип value) {
        this.грнипДата = value;
    }

    /**
     * Gets the value of the грнипДатаИспр property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНИПДатаТип }
     *     
     */
    public ГРНИПДатаТип getГРНИПДатаИспр() {
        return грнипДатаИспр;
    }

    /**
     * Sets the value of the грнипДатаИспр property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНИПДатаТип }
     *     
     */
    public void setГРНИПДатаИспр(ГРНИПДатаТип value) {
        this.грнипДатаИспр = value;
    }

    /**
     * Gets the value of the фамилия property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getФамилия() {
        return фамилия;
    }

    /**
     * Sets the value of the фамилия property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setФамилия(String value) {
        this.фамилия = value;
    }

    /**
     * Gets the value of the имя property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИмя() {
        return имя;
    }

    /**
     * Sets the value of the имя property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИмя(String value) {
        this.имя = value;
    }

    /**
     * Gets the value of the отчество property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОтчество() {
        return отчество;
    }

    /**
     * Sets the value of the отчество property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОтчество(String value) {
        this.отчество = value;
    }

}
