//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.27 at 05:20:15 PM IRKT 
//


package ru.sibdigital.proccovid.dto.egrip;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.sibdigital.egrul.dto.egrip package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.sibdigital.egrul.dto.egrip
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EGRIP }
     * 
     */
    public EGRIP createEGRIP() {
        return new EGRIP();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП }
     * 
     */
    public EGRIP.СвИП createEGRIPСвИП() {
        return new EGRIP.СвИП();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвЗапЕГРИП }
     * 
     */
    public EGRIP.СвИП.СвЗапЕГРИП createEGRIPСвИПСвЗапЕГРИП() {
        return new EGRIP.СвИП.СвЗапЕГРИП();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвЛицензия }
     * 
     */
    public EGRIP.СвИП.СвЛицензия createEGRIPСвИПСвЛицензия() {
        return new EGRIP.СвИП.СвЛицензия();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвРегФСС }
     * 
     */
    public EGRIP.СвИП.СвРегФСС createEGRIPСвИПСвРегФСС() {
        return new EGRIP.СвИП.СвРегФСС();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвРегПФ }
     * 
     */
    public EGRIP.СвИП.СвРегПФ createEGRIPСвИПСвРегПФ() {
        return new EGRIP.СвИП.СвРегПФ();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвУчетНО }
     * 
     */
    public EGRIP.СвИП.СвУчетНО createEGRIPСвИПСвУчетНО() {
        return new EGRIP.СвИП.СвУчетНО();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвПрекращ }
     * 
     */
    public EGRIP.СвИП.СвПрекращ createEGRIPСвИПСвПрекращ() {
        return new EGRIP.СвИП.СвПрекращ();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвСтатус }
     * 
     */
    public EGRIP.СвИП.СвСтатус createEGRIPСвИПСвСтатус() {
        return new EGRIP.СвИП.СвСтатус();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвРегИП }
     * 
     */
    public EGRIP.СвИП.СвРегИП createEGRIPСвИПСвРегИП() {
        return new EGRIP.СвИП.СвРегИП();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвАдрМЖ }
     * 
     */
    public EGRIP.СвИП.СвАдрМЖ createEGRIPСвИПСвАдрМЖ() {
        return new EGRIP.СвИП.СвАдрМЖ();
    }

    /**
     * Create an instance of {@link ВидЗапТип }
     * 
     */
    public ВидЗапТип createВидЗапТип() {
        return new ВидЗапТип();
    }

    /**
     * Create an instance of {@link ГородТип }
     * 
     */
    public ГородТип createГородТип() {
        return new ГородТип();
    }

    /**
     * Create an instance of {@link ГРНИПДатаТип }
     * 
     */
    public ГРНИПДатаТип createГРНИПДатаТип() {
        return new ГРНИПДатаТип();
    }

    /**
     * Create an instance of {@link ИдГРНИПДатаТип }
     * 
     */
    public ИдГРНИПДатаТип createИдГРНИПДатаТип() {
        return new ИдГРНИПДатаТип();
    }

    /**
     * Create an instance of {@link НаселПунктТип }
     * 
     */
    public НаселПунктТип createНаселПунктТип() {
        return new НаселПунктТип();
    }

    /**
     * Create an instance of {@link РайонТип }
     * 
     */
    public РайонТип createРайонТип() {
        return new РайонТип();
    }

    /**
     * Create an instance of {@link РегионТип }
     * 
     */
    public РегионТип createРегионТип() {
        return new РегионТип();
    }

    /**
     * Create an instance of {@link СвОКВЭДТип }
     * 
     */
    public СвОКВЭДТип createСвОКВЭДТип() {
        return new СвОКВЭДТип();
    }

    /**
     * Create an instance of {@link СвРегОргТип }
     * 
     */
    public СвРегОргТип createСвРегОргТип() {
        return new СвРегОргТип();
    }

    /**
     * Create an instance of {@link ФИО1Тип }
     * 
     */
    public ФИО1Тип createФИО1Тип() {
        return new ФИО1Тип();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвФЛ }
     * 
     */
    public EGRIP.СвИП.СвФЛ createEGRIPСвИПСвФЛ() {
        return new EGRIP.СвИП.СвФЛ();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвГражд }
     * 
     */
    public EGRIP.СвИП.СвГражд createEGRIPСвИПСвГражд() {
        return new EGRIP.СвИП.СвГражд();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвАдрЭлПочты }
     * 
     */
    public EGRIP.СвИП.СвАдрЭлПочты createEGRIPСвИПСвАдрЭлПочты() {
        return new EGRIP.СвИП.СвАдрЭлПочты();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвРегОрг }
     * 
     */
    public EGRIP.СвИП.СвРегОрг createEGRIPСвИПСвРегОрг() {
        return new EGRIP.СвИП.СвРегОрг();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвОКВЭД }
     * 
     */
    public EGRIP.СвИП.СвОКВЭД createEGRIPСвИПСвОКВЭД() {
        return new EGRIP.СвИП.СвОКВЭД();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвЗапЕГРИП.СведПредДок }
     * 
     */
    public EGRIP.СвИП.СвЗапЕГРИП.СведПредДок createEGRIPСвИПСвЗапЕГРИПСведПредДок() {
        return new EGRIP.СвИП.СвЗапЕГРИП.СведПредДок();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвЗапЕГРИП.СвСвид }
     * 
     */
    public EGRIP.СвИП.СвЗапЕГРИП.СвСвид createEGRIPСвИПСвЗапЕГРИПСвСвид() {
        return new EGRIP.СвИП.СвЗапЕГРИП.СвСвид();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвЗапЕГРИП.СвСтатусЗап }
     * 
     */
    public EGRIP.СвИП.СвЗапЕГРИП.СвСтатусЗап createEGRIPСвИПСвЗапЕГРИПСвСтатусЗап() {
        return new EGRIP.СвИП.СвЗапЕГРИП.СвСтатусЗап();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвЛицензия.СвПриостЛиц }
     * 
     */
    public EGRIP.СвИП.СвЛицензия.СвПриостЛиц createEGRIPСвИПСвЛицензияСвПриостЛиц() {
        return new EGRIP.СвИП.СвЛицензия.СвПриостЛиц();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвРегФСС.СвОргФСС }
     * 
     */
    public EGRIP.СвИП.СвРегФСС.СвОргФСС createEGRIPСвИПСвРегФСССвОргФСС() {
        return new EGRIP.СвИП.СвРегФСС.СвОргФСС();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвРегПФ.СвОргПФ }
     * 
     */
    public EGRIP.СвИП.СвРегПФ.СвОргПФ createEGRIPСвИПСвРегПФСвОргПФ() {
        return new EGRIP.СвИП.СвРегПФ.СвОргПФ();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвУчетНО.СвНО }
     * 
     */
    public EGRIP.СвИП.СвУчетНО.СвНО createEGRIPСвИПСвУчетНОСвНО() {
        return new EGRIP.СвИП.СвУчетНО.СвНО();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвПрекращ.СвСтатус }
     * 
     */
    public EGRIP.СвИП.СвПрекращ.СвСтатус createEGRIPСвИПСвПрекращСвСтатус() {
        return new EGRIP.СвИП.СвПрекращ.СвСтатус();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвПрекращ.СвНовЮЛ }
     * 
     */
    public EGRIP.СвИП.СвПрекращ.СвНовЮЛ createEGRIPСвИПСвПрекращСвНовЮЛ() {
        return new EGRIP.СвИП.СвПрекращ.СвНовЮЛ();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвСтатус.СвСтатус1 }
     * 
     */
    public EGRIP.СвИП.СвСтатус.СвСтатус1 createEGRIPСвИПСвСтатусСвСтатус() {
        return new EGRIP.СвИП.СвСтатус.СвСтатус1();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвРегИП.СвКФХ }
     * 
     */
    public EGRIP.СвИП.СвРегИП.СвКФХ createEGRIPСвИПСвРегИПСвКФХ() {
        return new EGRIP.СвИП.СвРегИП.СвКФХ();
    }

    /**
     * Create an instance of {@link EGRIP.СвИП.СвАдрМЖ.АдресРФ }
     * 
     */
    public EGRIP.СвИП.СвАдрМЖ.АдресРФ createEGRIPСвИПСвАдрМЖАдресРФ() {
        return new EGRIP.СвИП.СвАдрМЖ.АдресРФ();
    }

}
