//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.27 at 05:01:36 PM IRKT 
//


package ru.sibdigital.proccovid.dto.egrul;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.sibdigital.egrul.dto.egrul package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.sibdigital.egrul.dto.egrul
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EGRUL }
     * 
     */
    public EGRUL createEGRUL() {
        return new EGRUL();
    }

    /**
     * Create an instance of {@link СвОбремТип }
     * 
     */
    public СвОбремТип createСвОбремТип() {
        return new СвОбремТип();
    }

    /**
     * Create an instance of {@link ДоляУстКапЕГРЮЛТип }
     * 
     */
    public ДоляУстКапЕГРЮЛТип createДоляУстКапЕГРЮЛТип() {
        return new ДоляУстКапЕГРЮЛТип();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ }
     * 
     */
    public EGRUL.СвЮЛ createEGRULСвЮЛ() {
        return new EGRUL.СвЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвЗапЕГРЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвЗапЕГРЮЛ createEGRULСвЮЛСвЗапЕГРЮЛ() {
        return new EGRUL.СвЮЛ.СвЗапЕГРЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвПреем }
     * 
     */
    public EGRUL.СвЮЛ.СвПреем createEGRULСвЮЛСвПреем() {
        return new EGRUL.СвЮЛ.СвПреем();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвПредш }
     * 
     */
    public EGRUL.СвЮЛ.СвПредш createEGRULСвЮЛСвПредш() {
        return new EGRUL.СвЮЛ.СвПредш();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвРеорг }
     * 
     */
    public EGRUL.СвЮЛ.СвРеорг createEGRULСвЮЛСвРеорг() {
        return new EGRUL.СвЮЛ.СвРеорг();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвПодразд }
     * 
     */
    public EGRUL.СвЮЛ.СвПодразд createEGRULСвЮЛСвПодразд() {
        return new EGRUL.СвЮЛ.СвПодразд();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвЛицензия }
     * 
     */
    public EGRUL.СвЮЛ.СвЛицензия createEGRULСвЮЛСвЛицензия() {
        return new EGRUL.СвЮЛ.СвЛицензия();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит createEGRULСвЮЛСвУчредит() {
        return new EGRUL.СвЮЛ.СвУчредит();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрПИФ }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрПИФ createEGRULСвЮЛСвУчредитУчрПИФ() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрПИФ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО createEGRULСвЮЛСвУчредитУчрРФСубМО() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрФЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрФЛ createEGRULСвЮЛСвУчредитУчрФЛ() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрФЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрЮЛРос }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрЮЛРос createEGRULСвЮЛСвУчредитУчрЮЛРос() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрЮЛРос();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СведДолжнФЛ }
     * 
     */
    public EGRUL.СвЮЛ.СведДолжнФЛ createEGRULСвЮЛСведДолжнФЛ() {
        return new EGRUL.СвЮЛ.СведДолжнФЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУпрОрг }
     * 
     */
    public EGRUL.СвЮЛ.СвУпрОрг createEGRULСвЮЛСвУпрОрг() {
        return new EGRUL.СвЮЛ.СвУпрОрг();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвТипУстав }
     * 
     */
    public EGRUL.СвЮЛ.СвТипУстав createEGRULСвЮЛСвТипУстав() {
        return new EGRUL.СвЮЛ.СвТипУстав();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУстКап }
     * 
     */
    public EGRUL.СвЮЛ.СвУстКап createEGRULСвЮЛСвУстКап() {
        return new EGRUL.СвЮЛ.СвУстКап();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвРегФСС }
     * 
     */
    public EGRUL.СвЮЛ.СвРегФСС createEGRULСвЮЛСвРегФСС() {
        return new EGRUL.СвЮЛ.СвРегФСС();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвРегПФ }
     * 
     */
    public EGRUL.СвЮЛ.СвРегПФ createEGRULСвЮЛСвРегПФ() {
        return new EGRUL.СвЮЛ.СвРегПФ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвПрекрЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвПрекрЮЛ createEGRULСвЮЛСвПрекрЮЛ() {
        return new EGRUL.СвЮЛ.СвПрекрЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвСтатус }
     * 
     */
    public EGRUL.СвЮЛ.СвСтатус createEGRULСвЮЛСвСтатус() {
        return new EGRUL.СвЮЛ.СвСтатус();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвОбрЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвОбрЮЛ createEGRULСвЮЛСвОбрЮЛ() {
        return new EGRUL.СвЮЛ.СвОбрЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвАдресЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвАдресЮЛ createEGRULСвЮЛСвАдресЮЛ() {
        return new EGRUL.СвЮЛ.СвАдресЮЛ();
    }

    /**
     * Create an instance of {@link ВидЗапТип }
     * 
     */
    public ВидЗапТип createВидЗапТип() {
        return new ВидЗапТип();
    }

    /**
     * Create an instance of {@link АдрИнЕГРЮЛТип }
     * 
     */
    public АдрИнЕГРЮЛТип createАдрИнЕГРЮЛТип() {
        return new АдрИнЕГРЮЛТип();
    }

    /**
     * Create an instance of {@link АдрРФЕГРЮЛТип }
     * 
     */
    public АдрРФЕГРЮЛТип createАдрРФЕГРЮЛТип() {
        return new АдрРФЕГРЮЛТип();
    }

    /**
     * Create an instance of {@link ГородТип }
     * 
     */
    public ГородТип createГородТип() {
        return new ГородТип();
    }

    /**
     * Create an instance of {@link ГРНДатаТип }
     * 
     */
    public ГРНДатаТип createГРНДатаТип() {
        return new ГРНДатаТип();
    }

    /**
     * Create an instance of {@link ДробьТип }
     * 
     */
    public ДробьТип createДробьТип() {
        return new ДробьТип();
    }

    /**
     * Create an instance of {@link ИдГРНДатаТип }
     * 
     */
    public ИдГРНДатаТип createИдГРНДатаТип() {
        return new ИдГРНДатаТип();
    }

    /**
     * Create an instance of {@link НаселПунктТип }
     * 
     */
    public НаселПунктТип createНаселПунктТип() {
        return new НаселПунктТип();
    }

    /**
     * Create an instance of {@link РайонТип }
     * 
     */
    public РайонТип createРайонТип() {
        return new РайонТип();
    }

    /**
     * Create an instance of {@link РегионТип }
     * 
     */
    public РегионТип createРегионТип() {
        return new РегионТип();
    }

    /**
     * Create an instance of {@link РешСудТип }
     * 
     */
    public РешСудТип createРешСудТип() {
        return new РешСудТип();
    }

    /**
     * Create an instance of {@link СвНаимПодраздТип }
     * 
     */
    public СвНаимПодраздТип createСвНаимПодраздТип() {
        return new СвНаимПодраздТип();
    }

    /**
     * Create an instance of {@link СвНедДанУчрТип }
     * 
     */
    public СвНедДанУчрТип createСвНедДанУчрТип() {
        return new СвНедДанУчрТип();
    }

    /**
     * Create an instance of {@link СвНомТелТип }
     * 
     */
    public СвНомТелТип createСвНомТелТип() {
        return new СвНомТелТип();
    }

    /**
     * Create an instance of {@link СвНОТип }
     * 
     */
    public СвНОТип createСвНОТип() {
        return new СвНОТип();
    }

    /**
     * Create an instance of {@link СвНотУдДогЗалТип }
     * 
     */
    public СвНотУдДогЗалТип createСвНотУдДогЗалТип() {
        return new СвНотУдДогЗалТип();
    }

    /**
     * Create an instance of {@link СвОКВЭДТип }
     * 
     */
    public СвОКВЭДТип createСвОКВЭДТип() {
        return new СвОКВЭДТип();
    }

    /**
     * Create an instance of {@link СвРегИнЮЛЕГРЮЛТип }
     * 
     */
    public СвРегИнЮЛЕГРЮЛТип createСвРегИнЮЛЕГРЮЛТип() {
        return new СвРегИнЮЛЕГРЮЛТип();
    }

    /**
     * Create an instance of {@link СвРегОргТип }
     * 
     */
    public СвРегОргТип createСвРегОргТип() {
        return new СвРегОргТип();
    }

    /**
     * Create an instance of {@link СвУчетНОПодраздТип }
     * 
     */
    public СвУчетНОПодраздТип createСвУчетНОПодраздТип() {
        return new СвУчетНОПодраздТип();
    }

    /**
     * Create an instance of {@link СвФЛЕГРЮЛТип }
     * 
     */
    public СвФЛЕГРЮЛТип createСвФЛЕГРЮЛТип() {
        return new СвФЛЕГРЮЛТип();
    }

    /**
     * Create an instance of {@link СвЮЛЕГРЮЛТип }
     * 
     */
    public СвЮЛЕГРЮЛТип createСвЮЛЕГРЮЛТип() {
        return new СвЮЛЕГРЮЛТип();
    }

    /**
     * Create an instance of {@link УлицаТип }
     * 
     */
    public УлицаТип createУлицаТип() {
        return new УлицаТип();
    }

    /**
     * Create an instance of {@link ФИОТип }
     * 
     */
    public ФИОТип createФИОТип() {
        return new ФИОТип();
    }

    /**
     * Create an instance of {@link СвОбремТип.СвЗалогДержФЛ }
     * 
     */
    public СвОбремТип.СвЗалогДержФЛ createСвОбремТипСвЗалогДержФЛ() {
        return new СвОбремТип.СвЗалогДержФЛ();
    }

    /**
     * Create an instance of {@link СвОбремТип.СвЗалогДержЮЛ }
     * 
     */
    public СвОбремТип.СвЗалогДержЮЛ createСвОбремТипСвЗалогДержЮЛ() {
        return new СвОбремТип.СвЗалогДержЮЛ();
    }

    /**
     * Create an instance of {@link ДоляУстКапЕГРЮЛТип.РазмерДоли }
     * 
     */
    public ДоляУстКапЕГРЮЛТип.РазмерДоли createДоляУстКапЕГРЮЛТипРазмерДоли() {
        return new ДоляУстКапЕГРЮЛТип.РазмерДоли();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвНаимЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвНаимЮЛ createEGRULСвЮЛСвНаимЮЛ() {
        return new EGRUL.СвЮЛ.СвНаимЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвАдрЭлПочты }
     * 
     */
    public EGRUL.СвЮЛ.СвАдрЭлПочты createEGRULСвЮЛСвАдрЭлПочты() {
        return new EGRUL.СвЮЛ.СвАдрЭлПочты();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвРегОрг }
     * 
     */
    public EGRUL.СвЮЛ.СвРегОрг createEGRULСвЮЛСвРегОрг() {
        return new EGRUL.СвЮЛ.СвРегОрг();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчетНО }
     * 
     */
    public EGRUL.СвЮЛ.СвУчетНО createEGRULСвЮЛСвУчетНО() {
        return new EGRUL.СвЮЛ.СвУчетНО();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвДержРеестрАО }
     * 
     */
    public EGRUL.СвЮЛ.СвДержРеестрАО createEGRULСвЮЛСвДержРеестрАО() {
        return new EGRUL.СвЮЛ.СвДержРеестрАО();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвОКВЭД }
     * 
     */
    public EGRUL.СвЮЛ.СвОКВЭД createEGRULСвЮЛСвОКВЭД() {
        return new EGRUL.СвЮЛ.СвОКВЭД();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвКФХПредш }
     * 
     */
    public EGRUL.СвЮЛ.СвКФХПредш createEGRULСвЮЛСвКФХПредш() {
        return new EGRUL.СвЮЛ.СвКФХПредш();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвКФХПреем }
     * 
     */
    public EGRUL.СвЮЛ.СвКФХПреем createEGRULСвЮЛСвКФХПреем() {
        return new EGRUL.СвЮЛ.СвКФХПреем();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвЗапЕГРЮЛ.СведПредДок }
     * 
     */
    public EGRUL.СвЮЛ.СвЗапЕГРЮЛ.СведПредДок createEGRULСвЮЛСвЗапЕГРЮЛСведПредДок() {
        return new EGRUL.СвЮЛ.СвЗапЕГРЮЛ.СведПредДок();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвЗапЕГРЮЛ.СвСвид }
     * 
     */
    public EGRUL.СвЮЛ.СвЗапЕГРЮЛ.СвСвид createEGRULСвЮЛСвЗапЕГРЮЛСвСвид() {
        return new EGRUL.СвЮЛ.СвЗапЕГРЮЛ.СвСвид();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвЗапЕГРЮЛ.СвСтатусЗап }
     * 
     */
    public EGRUL.СвЮЛ.СвЗапЕГРЮЛ.СвСтатусЗап createEGRULСвЮЛСвЗапЕГРЮЛСвСтатусЗап() {
        return new EGRUL.СвЮЛ.СвЗапЕГРЮЛ.СвСтатусЗап();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвПреем.СвЮЛсложнРеорг }
     * 
     */
    public EGRUL.СвЮЛ.СвПреем.СвЮЛсложнРеорг createEGRULСвЮЛСвПреемСвЮЛсложнРеорг() {
        return new EGRUL.СвЮЛ.СвПреем.СвЮЛсложнРеорг();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвПредш.СвЮЛсложнРеорг }
     * 
     */
    public EGRUL.СвЮЛ.СвПредш.СвЮЛсложнРеорг createEGRULСвЮЛСвПредшСвЮЛсложнРеорг() {
        return new EGRUL.СвЮЛ.СвПредш.СвЮЛсложнРеорг();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвРеорг.СвСтатус }
     * 
     */
    public EGRUL.СвЮЛ.СвРеорг.СвСтатус createEGRULСвЮЛСвРеоргСвСтатус() {
        return new EGRUL.СвЮЛ.СвРеорг.СвСтатус();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвРеорг.СвРеоргЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвРеорг.СвРеоргЮЛ createEGRULСвЮЛСвРеоргСвРеоргЮЛ() {
        return new EGRUL.СвЮЛ.СвРеорг.СвРеоргЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвПодразд.СвФилиал }
     * 
     */
    public EGRUL.СвЮЛ.СвПодразд.СвФилиал createEGRULСвЮЛСвПодраздСвФилиал() {
        return new EGRUL.СвЮЛ.СвПодразд.СвФилиал();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвПодразд.СвПредстав }
     * 
     */
    public EGRUL.СвЮЛ.СвПодразд.СвПредстав createEGRULСвЮЛСвПодраздСвПредстав() {
        return new EGRUL.СвЮЛ.СвПодразд.СвПредстав();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвЛицензия.СвПриостЛиц }
     * 
     */
    public EGRUL.СвЮЛ.СвЛицензия.СвПриостЛиц createEGRULСвЮЛСвЛицензияСвПриостЛиц() {
        return new EGRUL.СвЮЛ.СвЛицензия.СвПриостЛиц();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрЮЛИн }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрЮЛИн createEGRULСвЮЛСвУчредитУчрЮЛИн() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрЮЛИн();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрПИФ.СвНаимПИФ }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрПИФ.СвНаимПИФ createEGRULСвЮЛСвУчредитУчрПИФСвНаимПИФ() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрПИФ.СвНаимПИФ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрПИФ.СвУпрКомпПИФ }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрПИФ.СвУпрКомпПИФ createEGRULСвЮЛСвУчредитУчрПИФСвУпрКомпПИФ() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрПИФ.СвУпрКомпПИФ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО.ВидНаимУчр }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО.ВидНаимУчр createEGRULСвЮЛСвУчредитУчрРФСубМОВидНаимУчр() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО.ВидНаимУчр();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО.СвОргОсущПр }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО.СвОргОсущПр createEGRULСвЮЛСвУчредитУчрРФСубМОСвОргОсущПр() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО.СвОргОсущПр();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО.СвФЛОсущПр }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО.СвФЛОсущПр createEGRULСвЮЛСвУчредитУчрРФСубМОСвФЛОсущПр() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрРФСубМО.СвФЛОсущПр();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрФЛ.СвДовУпрЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрФЛ.СвДовУпрЮЛ createEGRULСвЮЛСвУчредитУчрФЛСвДовУпрЮЛ() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрФЛ.СвДовУпрЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрФЛ.СвДовУпрФЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрФЛ.СвДовУпрФЛ createEGRULСвЮЛСвУчредитУчрФЛСвДовУпрФЛ() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрФЛ.СвДовУпрФЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрФЛ.ЛицоУпрНасл }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрФЛ.ЛицоУпрНасл createEGRULСвЮЛСвУчредитУчрФЛЛицоУпрНасл() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрФЛ.ЛицоУпрНасл();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУчредит.УчрЮЛРос.СвРегСтарые }
     * 
     */
    public EGRUL.СвЮЛ.СвУчредит.УчрЮЛРос.СвРегСтарые createEGRULСвЮЛСвУчредитУчрЮЛРосСвРегСтарые() {
        return new EGRUL.СвЮЛ.СвУчредит.УчрЮЛРос.СвРегСтарые();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СведДолжнФЛ.СвДолжн }
     * 
     */
    public EGRUL.СвЮЛ.СведДолжнФЛ.СвДолжн createEGRULСвЮЛСведДолжнФЛСвДолжн() {
        return new EGRUL.СвЮЛ.СведДолжнФЛ.СвДолжн();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СведДолжнФЛ.СвНедДанДолжнФЛ }
     * 
     */
    public EGRUL.СвЮЛ.СведДолжнФЛ.СвНедДанДолжнФЛ createEGRULСвЮЛСведДолжнФЛСвНедДанДолжнФЛ() {
        return new EGRUL.СвЮЛ.СведДолжнФЛ.СвНедДанДолжнФЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СведДолжнФЛ.СвДискв }
     * 
     */
    public EGRUL.СвЮЛ.СведДолжнФЛ.СвДискв createEGRULСвЮЛСведДолжнФЛСвДискв() {
        return new EGRUL.СвЮЛ.СведДолжнФЛ.СвДискв();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУпрОрг.СвНедДанУпрОрг }
     * 
     */
    public EGRUL.СвЮЛ.СвУпрОрг.СвНедДанУпрОрг createEGRULСвЮЛСвУпрОргСвНедДанУпрОрг() {
        return new EGRUL.СвЮЛ.СвУпрОрг.СвНедДанУпрОрг();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУпрОрг.СвПредЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвУпрОрг.СвПредЮЛ createEGRULСвЮЛСвУпрОргСвПредЮЛ() {
        return new EGRUL.СвЮЛ.СвУпрОрг.СвПредЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУпрОрг.ПредИнЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвУпрОрг.ПредИнЮЛ createEGRULСвЮЛСвУпрОргПредИнЮЛ() {
        return new EGRUL.СвЮЛ.СвУпрОрг.ПредИнЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвТипУстав.СвНПАУтвТУ }
     * 
     */
    public EGRUL.СвЮЛ.СвТипУстав.СвНПАУтвТУ createEGRULСвЮЛСвТипУставСвНПАУтвТУ() {
        return new EGRUL.СвЮЛ.СвТипУстав.СвНПАУтвТУ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвУстКап.СведУмУК }
     * 
     */
    public EGRUL.СвЮЛ.СвУстКап.СведУмУК createEGRULСвЮЛСвУстКапСведУмУК() {
        return new EGRUL.СвЮЛ.СвУстКап.СведУмУК();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвРегФСС.СвОргФСС }
     * 
     */
    public EGRUL.СвЮЛ.СвРегФСС.СвОргФСС createEGRULСвЮЛСвРегФСССвОргФСС() {
        return new EGRUL.СвЮЛ.СвРегФСС.СвОргФСС();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвРегПФ.СвОргПФ }
     * 
     */
    public EGRUL.СвЮЛ.СвРегПФ.СвОргПФ createEGRULСвЮЛСвРегПФСвОргПФ() {
        return new EGRUL.СвЮЛ.СвРегПФ.СвОргПФ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвПрекрЮЛ.СпПрекрЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвПрекрЮЛ.СпПрекрЮЛ createEGRULСвЮЛСвПрекрЮЛСпПрекрЮЛ() {
        return new EGRUL.СвЮЛ.СвПрекрЮЛ.СпПрекрЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвСтатус.СвСтатус1 }
     * 
     */
    public EGRUL.СвЮЛ.СвСтатус.СвСтатус1 createEGRULСвЮЛСвСтатусСвСтатус() {
        return new EGRUL.СвЮЛ.СвСтатус.СвСтатус1();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвСтатус.СвРешИсклЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвСтатус.СвРешИсклЮЛ createEGRULСвЮЛСвСтатусСвРешИсклЮЛ() {
        return new EGRUL.СвЮЛ.СвСтатус.СвРешИсклЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвОбрЮЛ.СпОбрЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвОбрЮЛ.СпОбрЮЛ createEGRULСвЮЛСвОбрЮЛСпОбрЮЛ() {
        return new EGRUL.СвЮЛ.СвОбрЮЛ.СпОбрЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвАдресЮЛ.СвНедАдресЮЛ }
     * 
     */
    public EGRUL.СвЮЛ.СвАдресЮЛ.СвНедАдресЮЛ createEGRULСвЮЛСвАдресЮЛСвНедАдресЮЛ() {
        return new EGRUL.СвЮЛ.СвАдресЮЛ.СвНедАдресЮЛ();
    }

    /**
     * Create an instance of {@link EGRUL.СвЮЛ.СвАдресЮЛ.СвРешИзмМН }
     * 
     */
    public EGRUL.СвЮЛ.СвАдресЮЛ.СвРешИзмМН createEGRULСвЮЛСвАдресЮЛСвРешИзмМН() {
        return new EGRUL.СвЮЛ.СвАдресЮЛ.СвРешИзмМН();
    }

}
