//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.27 at 05:01:36 PM IRKT 
//


package ru.sibdigital.proccovid.dto.egrul;

import javax.xml.bind.annotation.*;


/**
 * Сведения об адресе в РФ, внесенные в ЕГРЮЛ
 * 
 * <p>Java class for АдрРФЕГРЮЛТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="АдрРФЕГРЮЛТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Регион" type="{}РегионТип"/&gt;
 *         &lt;element name="Район" type="{}РайонТип" minOccurs="0"/&gt;
 *         &lt;element name="Город" type="{}ГородТип" minOccurs="0"/&gt;
 *         &lt;element name="НаселПункт" type="{}НаселПунктТип" minOccurs="0"/&gt;
 *         &lt;element name="Улица" type="{}УлицаТип" minOccurs="0"/&gt;
 *         &lt;element name="ГРНДата" type="{}ГРНДатаТип"/&gt;
 *         &lt;element name="ГРНДатаИспр" type="{}ГРНДатаТип" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Индекс"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;length value="6"/&gt;
 *             &lt;pattern value="[0-9]{6}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="КодРегион" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{}CCРФТип"&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="КодАдрКладр"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="11"/&gt;
 *             &lt;maxLength value="23"/&gt;
 *             &lt;pattern value="[0-9]{11}"/&gt;
 *             &lt;pattern value="[0-9]{15}"/&gt;
 *             &lt;pattern value="[0-9]{19}"/&gt;
 *             &lt;pattern value="[0-9]{23}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Дом"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="50"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Корпус"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="50"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Кварт"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="50"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0410\u0434\u0440\u0420\u0424\u0415\u0413\u0420\u042e\u041b\u0422\u0438\u043f", propOrder = {
    "\u0440\u0435\u0433\u0438\u043e\u043d",
    "\u0440\u0430\u0439\u043e\u043d",
    "\u0433\u043e\u0440\u043e\u0434",
    "\u043d\u0430\u0441\u0435\u043b\u041f\u0443\u043d\u043a\u0442",
    "\u0443\u043b\u0438\u0446\u0430",
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430",
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440"
})
public class АдрРФЕГРЮЛТип {

    @XmlElement(name = "\u0420\u0435\u0433\u0438\u043e\u043d", required = true)
    protected РегионТип регион;
    @XmlElement(name = "\u0420\u0430\u0439\u043e\u043d")
    protected РайонТип район;
    @XmlElement(name = "\u0413\u043e\u0440\u043e\u0434")
    protected ГородТип город;
    @XmlElement(name = "\u041d\u0430\u0441\u0435\u043b\u041f\u0443\u043d\u043a\u0442")
    protected НаселПунктТип населПункт;
    @XmlElement(name = "\u0423\u043b\u0438\u0446\u0430")
    protected УлицаТип улица;
    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430", required = true)
    protected ГРНДатаТип грнДата;
    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440")
    protected ГРНДатаТип грнДатаИспр;
    @XmlAttribute(name = "\u0418\u043d\u0434\u0435\u043a\u0441")
    protected String индекс;
    @XmlAttribute(name = "\u041a\u043e\u0434\u0420\u0435\u0433\u0438\u043e\u043d", required = true)
    protected String кодРегион;
    @XmlAttribute(name = "\u041a\u043e\u0434\u0410\u0434\u0440\u041a\u043b\u0430\u0434\u0440")
    protected String кодАдрКладр;
    @XmlAttribute(name = "\u0414\u043e\u043c")
    protected String дом;
    @XmlAttribute(name = "\u041a\u043e\u0440\u043f\u0443\u0441")
    protected String корпус;
    @XmlAttribute(name = "\u041a\u0432\u0430\u0440\u0442")
    protected String кварт;

    /**
     * Gets the value of the регион property.
     * 
     * @return
     *     possible object is
     *     {@link РегионТип }
     *     
     */
    public РегионТип getРегион() {
        return регион;
    }

    /**
     * Sets the value of the регион property.
     * 
     * @param value
     *     allowed object is
     *     {@link РегионТип }
     *     
     */
    public void setРегион(РегионТип value) {
        this.регион = value;
    }

    /**
     * Gets the value of the район property.
     * 
     * @return
     *     possible object is
     *     {@link РайонТип }
     *     
     */
    public РайонТип getРайон() {
        return район;
    }

    /**
     * Sets the value of the район property.
     * 
     * @param value
     *     allowed object is
     *     {@link РайонТип }
     *     
     */
    public void setРайон(РайонТип value) {
        this.район = value;
    }

    /**
     * Gets the value of the город property.
     * 
     * @return
     *     possible object is
     *     {@link ГородТип }
     *     
     */
    public ГородТип getГород() {
        return город;
    }

    /**
     * Sets the value of the город property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГородТип }
     *     
     */
    public void setГород(ГородТип value) {
        this.город = value;
    }

    /**
     * Gets the value of the населПункт property.
     * 
     * @return
     *     possible object is
     *     {@link НаселПунктТип }
     *     
     */
    public НаселПунктТип getНаселПункт() {
        return населПункт;
    }

    /**
     * Sets the value of the населПункт property.
     * 
     * @param value
     *     allowed object is
     *     {@link НаселПунктТип }
     *     
     */
    public void setНаселПункт(НаселПунктТип value) {
        this.населПункт = value;
    }

    /**
     * Gets the value of the улица property.
     * 
     * @return
     *     possible object is
     *     {@link УлицаТип }
     *     
     */
    public УлицаТип getУлица() {
        return улица;
    }

    /**
     * Sets the value of the улица property.
     * 
     * @param value
     *     allowed object is
     *     {@link УлицаТип }
     *     
     */
    public void setУлица(УлицаТип value) {
        this.улица = value;
    }

    /**
     * Gets the value of the грнДата property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДата() {
        return грнДата;
    }

    /**
     * Sets the value of the грнДата property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДата(ГРНДатаТип value) {
        this.грнДата = value;
    }

    /**
     * Gets the value of the грнДатаИспр property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДатаИспр() {
        return грнДатаИспр;
    }

    /**
     * Sets the value of the грнДатаИспр property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДатаИспр(ГРНДатаТип value) {
        this.грнДатаИспр = value;
    }

    /**
     * Gets the value of the индекс property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИндекс() {
        return индекс;
    }

    /**
     * Sets the value of the индекс property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИндекс(String value) {
        this.индекс = value;
    }

    /**
     * Gets the value of the кодРегион property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКодРегион() {
        return кодРегион;
    }

    /**
     * Sets the value of the кодРегион property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКодРегион(String value) {
        this.кодРегион = value;
    }

    /**
     * Gets the value of the кодАдрКладр property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКодАдрКладр() {
        return кодАдрКладр;
    }

    /**
     * Sets the value of the кодАдрКладр property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКодАдрКладр(String value) {
        this.кодАдрКладр = value;
    }

    /**
     * Gets the value of the дом property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getДом() {
        return дом;
    }

    /**
     * Sets the value of the дом property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setДом(String value) {
        this.дом = value;
    }

    /**
     * Gets the value of the корпус property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКорпус() {
        return корпус;
    }

    /**
     * Sets the value of the корпус property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКорпус(String value) {
        this.корпус = value;
    }

    /**
     * Gets the value of the кварт property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКварт() {
        return кварт;
    }

    /**
     * Sets the value of the кварт property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКварт(String value) {
        this.кварт = value;
    }

}
