//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.27 at 05:01:36 PM IRKT 
//


package ru.sibdigital.proccovid.dto.egrul;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * Доля в уставном капитале (складочном капитале, уставном фонде, паевом фонде), внесенная в ЕГРЮЛ
 * 
 * <p>Java class for ДоляУстКапЕГРЮЛТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ДоляУстКапЕГРЮЛТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="РазмерДоли" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Процент"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                         &lt;totalDigits value="18"/&gt;
 *                         &lt;fractionDigits value="15"/&gt;
 *                         &lt;minInclusive value="0"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ДробДесят"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                         &lt;totalDigits value="16"/&gt;
 *                         &lt;fractionDigits value="15"/&gt;
 *                         &lt;minInclusive value="0"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ДробПрост" type="{}ДробьТип"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ГРНДата" type="{}ГРНДатаТип"/&gt;
 *         &lt;element name="ГРНДатаИспр" type="{}ГРНДатаТип" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="НоминСтоим" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;totalDigits value="19"/&gt;
 *             &lt;fractionDigits value="4"/&gt;
 *             &lt;minInclusive value="0"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0414\u043e\u043b\u044f\u0423\u0441\u0442\u041a\u0430\u043f\u0415\u0413\u0420\u042e\u041b\u0422\u0438\u043f", propOrder = {
    "\u0440\u0430\u0437\u043c\u0435\u0440\u0414\u043e\u043b\u0438",
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430",
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440"
})
public class ДоляУстКапЕГРЮЛТип {

    @XmlElement(name = "\u0420\u0430\u0437\u043c\u0435\u0440\u0414\u043e\u043b\u0438")
    protected РазмерДоли размерДоли;
    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430", required = true)
    protected ГРНДатаТип грнДата;
    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440")
    protected ГРНДатаТип грнДатаИспр;
    @XmlAttribute(name = "\u041d\u043e\u043c\u0438\u043d\u0421\u0442\u043e\u0438\u043c", required = true)
    protected BigDecimal номинСтоим;

    /**
     * Gets the value of the размерДоли property.
     *
     * @return
     *     possible object is
     *     {@link РазмерДоли }
     *
     */
    public РазмерДоли getРазмерДоли() {
        return размерДоли;
    }

    /**
     * Sets the value of the размерДоли property.
     *
     * @param value
     *     allowed object is
     *     {@link РазмерДоли }
     *
     */
    public void setРазмерДоли(РазмерДоли value) {
        this.размерДоли = value;
    }

    /**
     * Gets the value of the грнДата property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДата() {
        return грнДата;
    }

    /**
     * Sets the value of the грнДата property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДата(ГРНДатаТип value) {
        this.грнДата = value;
    }

    /**
     * Gets the value of the грнДатаИспр property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДатаИспр() {
        return грнДатаИспр;
    }

    /**
     * Sets the value of the грнДатаИспр property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДатаИспр(ГРНДатаТип value) {
        this.грнДатаИспр = value;
    }

    /**
     * Gets the value of the номинСтоим property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getНоминСтоим() {
        return номинСтоим;
    }

    /**
     * Sets the value of the номинСтоим property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setНоминСтоим(BigDecimal value) {
        this.номинСтоим = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Процент"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *               &lt;totalDigits value="18"/&gt;
     *               &lt;fractionDigits value="15"/&gt;
     *               &lt;minInclusive value="0"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ДробДесят"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *               &lt;totalDigits value="16"/&gt;
     *               &lt;fractionDigits value="15"/&gt;
     *               &lt;minInclusive value="0"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ДробПрост" type="{}ДробьТип"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043f\u0440\u043e\u0446\u0435\u043d\u0442",
        "\u0434\u0440\u043e\u0431\u0414\u0435\u0441\u044f\u0442",
        "\u0434\u0440\u043e\u0431\u041f\u0440\u043e\u0441\u0442"
    })
    public static class РазмерДоли {

        @XmlElement(name = "\u041f\u0440\u043e\u0446\u0435\u043d\u0442")
        protected BigDecimal процент;
        @XmlElement(name = "\u0414\u0440\u043e\u0431\u0414\u0435\u0441\u044f\u0442")
        protected BigDecimal дробДесят;
        @XmlElement(name = "\u0414\u0440\u043e\u0431\u041f\u0440\u043e\u0441\u0442")
        protected ДробьТип дробПрост;

        /**
         * Gets the value of the процент property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getПроцент() {
            return процент;
        }

        /**
         * Sets the value of the процент property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setПроцент(BigDecimal value) {
            this.процент = value;
        }

        /**
         * Gets the value of the дробДесят property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getДробДесят() {
            return дробДесят;
        }

        /**
         * Sets the value of the дробДесят property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setДробДесят(BigDecimal value) {
            this.дробДесят = value;
        }

        /**
         * Gets the value of the дробПрост property.
         * 
         * @return
         *     possible object is
         *     {@link ДробьТип }
         *     
         */
        public ДробьТип getДробПрост() {
            return дробПрост;
        }

        /**
         * Sets the value of the дробПрост property.
         * 
         * @param value
         *     allowed object is
         *     {@link ДробьТип }
         *     
         */
        public void setДробПрост(ДробьТип value) {
            this.дробПрост = value;
        }

    }

}
