//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.27 at 05:01:36 PM IRKT 
//


package ru.sibdigital.proccovid.dto.egrul;

import javax.xml.bind.annotation.*;


/**
 * Сведения о недостоверности данных об учредителе (участнике)
 * 
 * <p>Java class for СвНедДанУчрТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="СвНедДанУчрТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="РешСудНедДанУчр" type="{}РешСудТип" minOccurs="0"/&gt;
 *         &lt;element name="ГРНДата" type="{}ГРНДатаТип"/&gt;
 *         &lt;element name="ГРНДатаИспр" type="{}ГРНДатаТип" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ПризнНедДанУчр" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;length value="1"/&gt;
 *             &lt;enumeration value="1"/&gt;
 *             &lt;enumeration value="2"/&gt;
 *             &lt;enumeration value="3"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ТекстНедДанУчр" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="500"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0421\u0432\u041d\u0435\u0434\u0414\u0430\u043d\u0423\u0447\u0440\u0422\u0438\u043f", propOrder = {
    "\u0440\u0435\u0448\u0421\u0443\u0434\u041d\u0435\u0434\u0414\u0430\u043d\u0423\u0447\u0440",
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430",
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440"
})
public class СвНедДанУчрТип {

    @XmlElement(name = "\u0420\u0435\u0448\u0421\u0443\u0434\u041d\u0435\u0434\u0414\u0430\u043d\u0423\u0447\u0440")
    protected РешСудТип решСудНедДанУчр;
    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430", required = true)
    protected ГРНДатаТип грнДата;
    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440")
    protected ГРНДатаТип грнДатаИспр;
    @XmlAttribute(name = "\u041f\u0440\u0438\u0437\u043d\u041d\u0435\u0434\u0414\u0430\u043d\u0423\u0447\u0440", required = true)
    protected String признНедДанУчр;
    @XmlAttribute(name = "\u0422\u0435\u043a\u0441\u0442\u041d\u0435\u0434\u0414\u0430\u043d\u0423\u0447\u0440", required = true)
    protected String текстНедДанУчр;

    /**
     * Gets the value of the решСудНедДанУчр property.
     * 
     * @return
     *     possible object is
     *     {@link РешСудТип }
     *     
     */
    public РешСудТип getРешСудНедДанУчр() {
        return решСудНедДанУчр;
    }

    /**
     * Sets the value of the решСудНедДанУчр property.
     * 
     * @param value
     *     allowed object is
     *     {@link РешСудТип }
     *     
     */
    public void setРешСудНедДанУчр(РешСудТип value) {
        this.решСудНедДанУчр = value;
    }

    /**
     * Gets the value of the грнДата property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДата() {
        return грнДата;
    }

    /**
     * Sets the value of the грнДата property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДата(ГРНДатаТип value) {
        this.грнДата = value;
    }

    /**
     * Gets the value of the грнДатаИспр property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДатаИспр() {
        return грнДатаИспр;
    }

    /**
     * Sets the value of the грнДатаИспр property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДатаИспр(ГРНДатаТип value) {
        this.грнДатаИспр = value;
    }

    /**
     * Gets the value of the признНедДанУчр property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getПризнНедДанУчр() {
        return признНедДанУчр;
    }

    /**
     * Sets the value of the признНедДанУчр property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setПризнНедДанУчр(String value) {
        this.признНедДанУчр = value;
    }

    /**
     * Gets the value of the текстНедДанУчр property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getТекстНедДанУчр() {
        return текстНедДанУчр;
    }

    /**
     * Sets the value of the текстНедДанУчр property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setТекстНедДанУчр(String value) {
        this.текстНедДанУчр = value;
    }

}
