//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.27 at 05:01:36 PM IRKT 
//


package ru.sibdigital.proccovid.dto.egrul;

import javax.xml.bind.annotation.*;


/**
 * Сведения о виде деятельности, внесенном в ЕГРЮЛ
 * 
 * <p>Java class for СвОКВЭДТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="СвОКВЭДТип"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ГРНДата" type="{}ГРНДатаТип"/&gt;
 *         &lt;element name="ГРНДатаИспр" type="{}ГРНДатаТип" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="КодОКВЭД" use="required" type="{}ОКВЭДТип" /&gt;
 *       &lt;attribute name="НаимОКВЭД" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;maxLength value="1000"/&gt;
 *             &lt;minLength value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ПрВерсОКВЭД"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;length value="4"/&gt;
 *             &lt;enumeration value="2001"/&gt;
 *             &lt;enumeration value="2014"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0421\u0432\u041e\u041a\u0412\u042d\u0414\u0422\u0438\u043f", propOrder = {
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430",
    "\u0433\u0440\u043d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440"
})
public class СвОКВЭДТип {

    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430", required = true)
    protected ГРНДатаТип грнДата;
    @XmlElement(name = "\u0413\u0420\u041d\u0414\u0430\u0442\u0430\u0418\u0441\u043f\u0440")
    protected ГРНДатаТип грнДатаИспр;
    @XmlAttribute(name = "\u041a\u043e\u0434\u041e\u041a\u0412\u042d\u0414", required = true)
    protected String кодОКВЭД;
    @XmlAttribute(name = "\u041d\u0430\u0438\u043c\u041e\u041a\u0412\u042d\u0414", required = true)
    protected String наимОКВЭД;
    @XmlAttribute(name = "\u041f\u0440\u0412\u0435\u0440\u0441\u041e\u041a\u0412\u042d\u0414")
    protected String прВерсОКВЭД;

    /**
     * Gets the value of the грнДата property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДата() {
        return грнДата;
    }

    /**
     * Sets the value of the грнДата property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДата(ГРНДатаТип value) {
        this.грнДата = value;
    }

    /**
     * Gets the value of the грнДатаИспр property.
     * 
     * @return
     *     possible object is
     *     {@link ГРНДатаТип }
     *     
     */
    public ГРНДатаТип getГРНДатаИспр() {
        return грнДатаИспр;
    }

    /**
     * Sets the value of the грнДатаИспр property.
     * 
     * @param value
     *     allowed object is
     *     {@link ГРНДатаТип }
     *     
     */
    public void setГРНДатаИспр(ГРНДатаТип value) {
        this.грнДатаИспр = value;
    }

    /**
     * Gets the value of the кодОКВЭД property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКодОКВЭД() {
        return кодОКВЭД;
    }

    /**
     * Sets the value of the кодОКВЭД property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКодОКВЭД(String value) {
        this.кодОКВЭД = value;
    }

    /**
     * Gets the value of the наимОКВЭД property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНаимОКВЭД() {
        return наимОКВЭД;
    }

    /**
     * Sets the value of the наимОКВЭД property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНаимОКВЭД(String value) {
        this.наимОКВЭД = value;
    }

    /**
     * Gets the value of the прВерсОКВЭД property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getПрВерсОКВЭД() {
        return прВерсОКВЭД;
    }

    /**
     * Sets the value of the прВерсОКВЭД property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setПрВерсОКВЭД(String value) {
        this.прВерсОКВЭД = value;
    }

}
